### ISSUE TITLE
Should we remove the static parameters scenario?

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/katacoda-scenarios#16]
Seems to be creating a lot of confusion. I would rather give people `params_from_vars` straight away

@oybed @etsauer thoughts?

**Comment by oybed** [comment]
@pcarney8 do you have some additional information to share about the "confusion"? Has there been issues raised, or some other communication that we haven't seen? 

I don't think it's a good idea to remove one of the main capabilities from the tutorials, but maybe there's room for improvements to avoid confusions(?).

**Comment by pcarney8** [comment]
@oybed Confusion was brought up by customer, they didn't understand they were capable of using files or ansible variables. 

I think it was mainly due to the amount of material they had to learn in a short period of time. I'm going to close this. 

I think having something like #17 will help reinforce that they actually learned what they went through.

**Comment by etsauer** [comment]
@pcarney8 i see you already closed this, but my two cents is that we should present BOTH methods side-by-side in the scanario right from the get-go.

**Comment by pcarney8** [comment]
@etsauer putting both in the same scenario will increase the density of the material and make it even harder to learn. I'm just going to leave these as they are and work on #17 to reinforce concepts so that people can learn how to create what they need more free form.
